version: '3.7'

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-master}
      - POSTGRES_PASSWORD=${DB_PASS:-password}
      - POSTGRES_DB=${DB_NAME:-currencies}
