service: 'currency-explorer'
frameworkVersion: '3'
variablesResolutionMode: 20210326

package:
  patterns:
   - '*'
   - '!node_modules/**'

provider:
 name: aws
 runtime: python3.9
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 api:
   handler: wsgi_handler.handler
   events:
    - http: ANY /
    - http: ANY /{proxy+}