"""Fixed correct numeric precision

Revision ID: c139478f03e2
Revises: 79edc6310f1e
Create Date: 2023-01-09 21:04:35.581505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c139478f03e2'
down_revision = '79edc6310f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.alter_column('dollar_buy',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('dollar_sell',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('euro_buy',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('euro_sell',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.alter_column('euro_sell',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
        batch_op.alter_column('euro_buy',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
        batch_op.alter_column('dollar_sell',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
        batch_op.alter_column('dollar_buy',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###
