"""Bank and exchange models

Revision ID: 79edc6310f1e
Revises: 
Create Date: 2023-01-02 18:27:55.986086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79edc6310f1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dollar_buy', sa.Numeric(precision=2), nullable=True),
    sa.Column('dollar_sell', sa.Numeric(precision=2), nullable=True),
    sa.Column('euro_buy', sa.Numeric(precision=2), nullable=True),
    sa.Column('euro_sell', sa.Numeric(precision=2), nullable=True),
    sa.Column('bank_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange')
    op.drop_table('bank')
    # ### end Alembic commands ###
