name: Branch CI
on:
  push:
    branches:
      - '**'      # matches every branch
      - '!main'   # excludes main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setting up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Setting up node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.1
    - name: Run unit tests
      run: npm run unit-tests

